[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "serverless/api"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
